language: objective-c
os: osx
osx_image: xcode8
xcode_project: APNGKit.xcodeproj
xcode_scheme: APNGKit

script: 
- |
    set -o pipefail
    xcodebuild clean test -project APNGKit.xcodeproj -scheme APNGKit -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' | xcpretty

git:
  submodules: false
