language: objective-c
os: osx
osx_image: xcode7
xcode_project: APNGKit.xcodeproj
xcode_scheme: APNGKit

script: xctool -project APNGKit.xcodeproj -scheme APNGKit test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

git:
  submodules: false
